### ISSUE TITLE
Lock determineWinner() so the price gets transferred only once

### ISSUE THREAD

**Issue by HandradeG** [garrison1234/Hashminer#10]

**Comment by garrison1234** [comment]
I think determineWinner() is already locked. It requires playerCounter == maxNumberOfPlayers, and playerCounter is reset to 0 after running it once. Functions cannot be called in parallel in ethereum. From what I understand, if they're called several times within one block the miner sets an order for the execution, so after the first execution, it would be locked. The caller would lose the gas necessary to call it.

**Comment by garrison1234** [comment]
I think we need to do this on the front-end. For example, have a button for "show Winner!" that only activates for a user with a given address at a time, to avoid 2 players calling the function in the same block and wasting ether. The button could be activated for one user, then another, and so on.

**Comment by garrison1234** [comment]
If an "attacker" wants to call it before that.. better for us. The only way they could affect anyone is if they deliberately tried to call determineWinner() at the same time as another player to make them waste money.

**Comment by garrison1234** [comment]
Solved
